# Generic labels
- name: bug
  description: Something isn't working
  color: d73a4a
- name: documentation
  description: Improvements or additions to documentation
  color: 0075ca
- name: duplicate
  description: This issue or pull request already exists
  color: cfd3d7
- name: enhancement
  description: New feature or request
  color: a2eeef
- name: good first issue
  description: Good for newcomers
  color: 7057ff
- name: help wanted
  description: Extra attention is needed
  color: 008672
- name: invalid
  description: This doesn't seem right
  color: e4e669
- name: wontfix
  description: This will not be worked on
  color: ffffff
- name: blocked
  description: This issue is blocked by some other work
  color: e0af74
- name: critical
  description: This issue needs critical attention
  color: B60205
- name: infra
  description: Infra, devops, CI and related tasks
  color: 277196
- name: milestone
  description: Tracks a subteam milestone
  color: 1CC0B0
- name: epic
  description: Tracks a yearly team epic (only for waku-org/pm repo)
  color: 07544B
- name: test
  description: Issue related to the test suite with no expected consequence to production code
  color: 277196
- name: release-notes
  description: Issue/PR needs to be evaluated for inclusion in release notes highlights or upgrade instructions
  color: fb3c99
- name: dependencies
  description: Pull requests that update a dependency file or issues that track it
  color: 0366d6

# Tracks
- name: track:rln
  description: RLN Track (Secure Messaging/Applied ZK), e.g. relay and applications
  color: C89BC6
- name: track:anonymity
  description: Anonymity track (Secure Messaging)
  color: 06B6C8
- name: track:operator-outreach
  description: Operator outreach track (Secure Messaging/Waku Product)
  color: B888AB
- name: track:ft-store
  description: FT-Store track (Secure Messaging)
  color: F5FD62
- name: track:discovery
  description: Discovery track (Secure Messaging/Waku Product)
  color: 6BEB61
- name: track:protocol-incentivization
  description: Protocol Incentivization track (Secure Messaging), e.g. service credentials
  color: 0037E3
- name: track:restricted-run
  description: Restricted run track (Secure Messaging/Waku Product), e.g. filter, WebRTC
  color: D91C35
- name: track:conversational-security
  description: Conversational security track (Secure Messaging)
  color: CC6B00
- name: track:nwaku-productionization
  description: nwaku productionization track (Waku Product)
  color: 9DEA79
- name: track:nwaku-maintenance
  description: nwaku maintenance track (Waku Product)
  color: 40F9F0
- name: track:network-testing
  description: Network testing track (Secure Messaging/Waku Product)
  color: bfd4f2
- name: track:platform-outreach
  description: Platform outreach track (Waku Product)
  color: 06B6C8
- name: track:sdks
  description: SDKS track (Waku Product), including bindings
  color: 34D557
- name: track:go-waku-productionization
  description: go-waku productionization track (Waku Product)
  color: 9DEA79

# Epics

## Old Epics to Remove
- name: E:2023-light-protocols
  description: https://github.com/waku-org/pm/issues/25
  color: FEF445
- name: E:2023-10k-users
  description: https://github.com/waku-org/pm/issues/12
  color: 0052cc
- name: E:2023-1mil-users
  description: https://github.com/waku-org/pm/issues/31
  color: 24B684
- name: E:2023-dev-rel-assets
  description: https://github.com/waku-org/pm/issues/32
  color: FACBD4
- name: E:2023-peer-mgmt
  description: https://github.com/waku-org/pm/issues/33
  color: 6D5261
- name: E:2023-metrics
  description: https://github.com/waku-org/pm/issues/35
  color: 2B4DAF
- name: E:2023-eco-growth
  description: https://github.com/waku-org/pm/issues/36
  color: 9CC0E8
- name: E:2023-rln
  description: https://github.com/waku-org/pm/issues/37
  color: E9B7A4
- name: E:2023-incentivize-operators
  description: https://github.com/waku-org/pm/issues/38
  color: 41C5E6
- name: E:2023-many-platforms
  description: https://github.com/waku-org/pm/issues/42
  color: e99695

## Orphan Epics
- name: "E:Define network and community metrics"
  description: https://github.com/waku-org/pm/issues/35
  color: 2B4DAF
- name: "E:Comprehensive dev testing"
  description: https://github.com/waku-org/pm/issues/90
  color: 088DF8


## [Milestone] Waku Network Can Support 10K Users
- name: "E:Static sharding"
  description: https://github.com/waku-org/pm/issues/15
  color: b60205
- name: "E:Opt-in message signing"
  description: https://github.com/waku-org/pm/issues/20
  color: 10C366

## [Milestone] Support Many Platforms
- name: "E:NodeJS Library"
  description: https://github.com/waku-org/pm/issues/81
  color: fef2c0
- name: "E:REST API service node"
  description: https://github.com/waku-org/pm/issues/82
  color: bfd4f2
- name: "E:RLN non-native SDKs"
  description: https://github.com/waku-org/pm/issues/88
  color: 3CDF39

## [Milestone] Waku Network can Support 1 Million Users
- name: "E:PostgreSQL"
  description: https://github.com/waku-org/pm/issues/84
  color: 35DCCC
- name: "E:Node for professional operators"
  description: https://github.com/waku-org/pm/issues/92
  color: 6E7C80

## [Milestone] Waku Network Gen 0
- name: "E:1.1 Network requirements and task breakdown"
  description: https://github.com/waku-org/pm/issues/62
  color: 20A609
- name: "E:1.2: Autosharding for autoscaling"
  description: https://github.com/waku-org/pm/issues/65
  color: 5319e7
- name: "E:1.3: Node bandwidth management mechanism"
  description: https://github.com/waku-org/pm/issues/66
  color: 8A5EE0
- name: "E:1.4: Sharded peer management and discovery"
  description: https://github.com/waku-org/pm/issues/67
  color: 244B5B
- name: "E:1.5: Launch and dogfood integrated WN MVP"
  description: https://github.com/waku-org/pm/issues/68
  color: 195A49
- name: "E:2.1: Production testing of existing protocols"
  description: https://github.com/waku-org/pm/issues/49
  color: e99695
- name: "E:2.2: Sharded cap discovery for light protocols"
  description: https://github.com/waku-org/pm/issues/63
  color: 92A880
- name: "E:2.3: Basic distributed Store services"
  description: https://github.com/waku-org/pm/issues/64
  color: 37BEA9
- name: "E:3.1: DoS requirements and design"
  description: https://github.com/waku-org/pm/issues/69
  color: B342EA
- name: "E:3.2: Basic DoS protection in production"
  description: https://github.com/waku-org/pm/issues/70
  color: DF42D5
- name: "E:3.4: Production and memberships on mainnet"
  description: https://github.com/waku-org/pm/issues/87
  color: e99695


## [Milestone] Quality Assurance processes are in place
- name: "E:Automated release processes"
  description: https://github.com/waku-org/pm/issues/86
  color: 0052cc
- name: "E:End-to-end testing"
  description: https://github.com/waku-org/pm/issues/34
  color: bfd4f2
